### ISSUE TITLE
Production checklist

### ISSUE THREAD

**Issue by pj00** [CCOMIT/CSO#22]
- [x] Deploy tables with "force column order" option.  Afterwards, you'll need to re-grant permissions.  Make sure you grant on all pertinent schemas: [audit], [cr], [lu], [ip], etc.  Also, make sure you grant SELECT and EXECUTE permissions to SSRS role.
- [x] Run script from comment below.
- [x] Were [audit] tables updated to account for new changes?
- [ ] Review TODO: items

**Comment by pj00** [comment]
UPDATE [CSO].[cr].[People] SET [SexualMisconductFlag] = 2
  UPDATE [CSO].[cr].[People] SET WellmarkDegree = 11 WHERE Title = 'DDS' OR Title LIKE 'DDS %'
  UPDATE [CSO].[cr].[People] SET WellmarkDegree = 13 WHERE Title = 'MD' OR Title LIKE 'MD %'
  UPDATE [CSO].[cr].[People] SET WellmarkDegree = 15 WHERE Title = 'DO' OR Title LIKE 'DO %'
